name: GitHub Activity

# runs every saturday midnight & when pushed to master

on:
  schedule:
    - cron: '0 0 * * 6'
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)

          # Options
          token: ${{ secrets.METRICS_TOKEN }}
          user: obaydullahmhs
          template: classic
          base: header, activity, repositories, metadata
          config_display: columns
          config_octicon: yes
          config_timezone: Asia/Dhaka
          plugin_leetcode: yes
          # plugin_leetcode_limit_recent: 2
          # plugin_leetcode_limit_skills: 10
          # plugin_leetcode_sections: solved
          # plugin_leetcode_user: obaydullahmhs
          plugin_lines: yes
          plugin_lines_history_limit: 8
          plugin_lines_repositories_limit: 0
          plugin_lines_sections: base
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_user: 7360615
          plugin_topics: yes
          plugin_topics_limit: 5
          plugin_topics_mode: starred
          plugin_topics_sort: starred
